name: Inspect
on: [push]

jobs:
  test:
    name: Inspect GraphQL schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
 
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: .\schema\main.graphql