services:

  gateway-api:
    container_name: fwdays-gateway-api
    image: fwdays-gateway-api
    build:
      context: .
      dockerfile: ./src/FWDays.Gateway/Dockerfile
    environment:
      - ConnectionStrings__Redis=192.168.0.105:6379,password=fwdpass
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 9000:8080
    depends_on:
      - speakers-api
      - participants-api
      - tracks-api
      - redis

  speakers-api:
    container_name: fwdays-speakers-api
    image: fwdays-speakers-api
    build:
      context: .
      dockerfile: ./src/FWDays.Speakers/Dockerfile
    environment:
      - ConnectionStrings__Database=Host=192.168.0.105;Port=5432;Database=fwdays-2024;User ID=fwduser;Password=fwdpass;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 9001:8080
    depends_on:
      - db

  tracks-api:
    container_name: fwdays-tracks-api
    image: fwdays-tracks-api
    build:
      context: .
      dockerfile: ./src/FWDays.Tracks/Dockerfile
    environment:
      - ConnectionStrings__Database=Host=192.168.0.105;Port=5432;Database=fwdays-2024;User ID=fwduser;Password=fwdpass;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 9002:8080
    depends_on:
      - db

  participants-api:
    container_name: fwdays-participants-api
    image: fwdays-participants-api
    build:
      context: .
      dockerfile: ./src/FWDays.Participants/Dockerfile
    environment:
      - ConnectionStrings__Database=Host=192.168.0.105;Port=5432;Database=fwdays-2024;User ID=fwduser;Password=fwdpass;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 9003:8080
    depends_on:
      - db

  db:
    container_name: fwdays-postgres-db
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "fwdays-2024"
      POSTGRES_USER: "fwduser"
      POSTGRES_PASSWORD: "fwdpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fwduser -d fwdays-2024" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  redis:
    container_name: fwdays-redis-db
    image: redis:7.2.5-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/root/redis
      - ./redis-data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=fwdpass
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
