services:

  gateway-api:
    container_name: fwdays-gateway-api
    image: fwdays-gateway-api
    build:
      context: .
      dockerfile: ./src/FWDays.Gateway/Dockerfile
    environment:
      - GraphQL__ServiceName=gateway
      - GraphQL__Redis=redis:6379,password=fwdpass
      - GraphQL__DetailedErrors=true
      - GraphQL__Services__0__Name=speakers
      - GraphQL__Services__0__Url=http://192.168.0.101:9001/graphql
      - GraphQL__Services__1__Name=tracks
      - GraphQL__Services__1__Url=http://192.168.0.101:9002/graphql
      - GraphQL__Services__2__Name=participants
      - GraphQL__Services__2__Url=http://192.168.0.101:9003/graphql
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 9000:8080
    depends_on:
        speakers-api:
          condition: service_started
        participants-api:
          condition: service_started
        tracks-api:
          condition: service_started

  speakers-api:
    container_name: fwdays-speakers-api
    image: fwdays-speakers-api
    build:
      context: .
      dockerfile: ./src/FWDays.Speakers/Dockerfile
    environment:
      - ConnectionStrings__Database=Host=db;Port=5432;Database=fwdays-2024-speakers;User ID=fwduser;Password=fwdpass;
      - GraphQL__Redis=redis:6379,password=fwdpass
      - GraphQL__Federation=true
      - GraphQL__DetailedErrors=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 9001:8080
    depends_on:
        redis:
          condition: service_healthy
        db:
          condition: service_healthy

  tracks-api:
    container_name: fwdays-tracks-api
    image: fwdays-tracks-api
    build:
      context: .
      dockerfile: ./src/FWDays.Tracks/Dockerfile
    environment:
      - ConnectionStrings__Database=Host=db;Port=5432;Database=fwdays-2024-tracks;User ID=fwduser;Password=fwdpass;
      - GraphQL__Redis=redis:6379,password=fwdpass
      - GraphQL__Federation=true
      - GraphQL__DetailedErrors=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 9002:8080
    depends_on:
        redis:
          condition: service_healthy
        db:
          condition: service_healthy

  participants-api:
    container_name: fwdays-participants-api
    image: fwdays-participants-api
    build:
      context: .
      dockerfile: ./src/FWDays.Participants/Dockerfile
    environment:
      - ConnectionStrings__Database=Host=db;Port=5432;Database=fwdays-2024-participants;User ID=fwduser;Password=fwdpass;
      - GraphQL__Redis=redis:6379,password=fwdpass
      - GraphQL__Federation=true
      - GraphQL__DetailedErrors=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - 9003:8080
    depends_on:
        redis:
          condition: service_healthy
        db:
          condition: service_healthy

  db:
    container_name: fwdays-postgres-db
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: "fwduser"
      POSTGRES_PASSWORD: "fwdpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./.db-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fwduser -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  redis:
    container_name: fwdays-redis-db
    image: redis:7.2.5-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - ./.db-redis:/root/redis
      - ./.db-redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=fwdpass
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
