name: Inspect
on:
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  contents: read 
  pull-requests: write
  security-events: write
  checks: write

jobs:
  test:
    name: Inspect GraphQL schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
 
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: ./schema/main.graphql
